using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.GamerServices;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Media;

namespace VoxelCovvEngine
{
    public abstract class WorldGenerator
    {
        public WorldGenerator()
        {

        }
        
        /// <summary>
        /// Gets the world generated by the 'WorldGenerator.World' property.
        /// </summary>
        /// <returns>A VoxelWorld object</returns>
        public VoxelWorld  Generate()
        {
            return World;
        }

        /// <summary>
        /// Code for generating the world
        /// </summary>
        protected abstract VoxelWorld World { get; }

        public class Void : WorldGenerator
        {
            public Void() : base() { }

            protected override VoxelWorld World
            {
                get { return new VoxelWorld(1,1); }
            }
        }
    }
}
